### PR TITLE
GTK3

### PR DESCRIPTION
**Pull request by M7S**
Fully function gtk3 port?

### CODE REVIEW

**Comment by M7S** [comment]
@twa022 Is this a fully functional gtk3 port?

I get this error when I run ./waf build:
error: Package `libxfce4panel-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `libxfconf-0' not found in specified Vala API directories or GObject-Introspection GIR directories

even though ./waf configure says
Checking for 'libxfce4panel-2.0'         : yes 
Checking for 'libxfconf-0'               : yes

Is this a bug or did I do something wrong?

**Comment by twa022** [comment]
@M7S I think the issue must be that *buntu doesn't package the vapi files from the xfce4 dependencies, whereas archlinux which I tested it on does.
I just pushed commits to my branch where I copied the vapi files from my current xfce4 install (xfce4-panel: 4.14.4, xfconf 4.14.3, libxfce4ui 4.14.1) to a directory in the source tree and updated wscript to know to use them if the files cannot be found in the system vapi directory. Let me know if you can compile successfully now.

There are a few issues with my branch that I know of and haven't had a chance to look into:
If you choose blend with panel it does not select the correct color for all themes (works fine for Numix, but with Arc selects a light color even though the panel is dark -- I think that code is in the python plug, is it selecting the wrong CSS value?)

If you select Solid Color for the plugin background color the value is stored in xfconf as 'rgb(r, g, b)', but should be stored as '#rrggbb'. If you leave it and don't manually change the value in xfconf or switch to blend with panel the plugin will crash the next time it is loaded.

**Comment by M7S** [comment]
That's progress, I can build now. Installing with `sudo ./waf install`still fails with the message:
```Package `libxfce4util-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories```

I will look into the blend with panel bug when I get it installed.

**Comment by twa022** [comment]
@m7s
I'll add the libxfce4util vapi files and push when I have a sec this afternoon.

I remembered that arc theme had been unmaintained for a while, so it could be an issue with an outdated theme rather than in the program logic.

Also now that I'm adding the vapi files locally, we might be able to push the xfce component requirements down to 4.12. are you running *buntu 18.04 that you could check?

**Comment by M7S** [comment]
I still run 18.04 on my laptop so I can check when you've added the missing vapi files.


I thought the arc theme problem was a regression but apparently I never tried using arc theme. I've tried a handful other themes and they all seem to be working. I will still look into it. I don't believe that the problem is that arc theme is too outdated. Just ten months ago there was a commit to arc theme fixing some xfce4-panel 4.14 stuff (not connected to background color, though).

**Comment by twa022** [comment]
I added the libxfce4util vapi file and dropped the version requirements in the wscript file (I can revert that commit if it doesn't work)

**Comment by M7S** [comment]
It seems to be working, both on xubuntu 20.04 and 18.04. Not that I have any way to tell if I'm running the gtk3 socket or the old gtk2 socket that was installed previously but the install process as it should, so I guess everything is in order. Thank you for making this.

**Pull request merged**
